# -*- coding: utf-8 -*-
"""TSNE_Morgan2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ce3PIWuuQcWjO2Th6mtKwdfgd7Ssv2uK
"""

#Load modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.manifold import TSNE
from pathlib import Path

# Compounds
db_novo = pd.read_csv(Path.home() /'Documentos'/'Vero'/'FBDD_DB_DiVer'/'Scrips_caracterización_denovo'/ 'allcompounds_denovo.csv')
db_novo.tail(2)

# Save Dataframe
#"from google.colab import drive
#"drive.mount('/content/drive', force_remount=True)
#df.to_csv("TSNE_ECFP4_ALL.csv", sep=",", index=False)

from rdkit import Chem
from rdkit.Chem import MACCSkeys, AllChem
from scipy.spatial.distance import pdist

# Check for invalid SMILES strings
data1 = db_novo.copy()

# Check for invalid SMILES strings
invalid_smiles = [x for x in data1['SMILES_curated'] if Chem.MolFromSmiles(x) is None]

# Print the invalid SMILES strings
print(f"Invalid SMILES strings: {invalid_smiles}")

# Remove the invalid SMILES strings from the DataFrame
data1 = data1[~data1['SMILES_curated'].isin(invalid_smiles)]

# Recalculate the Morgan2
fps = [[int(y) for y in AllChem.GetMorganFingerprintAsBitVect(Chem.MolFromSmiles(x), 2, nBits=1024).ToBitString()] for x in data1['SMILES_curated']]
fps = pd.DataFrame([np.array(x) for x in fps])
fps

len(fps)

# Training t-SNE
from sklearn.manifold import TSNE
from sklearn.preprocessing import StandardScaler
data_tsne = fps
#data_tsne = data_tsne.drop(labels = ["Data set", "ID","SMILES"],axis = 1)
#data_tsne = StandardScaler().fit_transform(data_tsne)
tsne = TSNE(n_components=2, verbose=1, perplexity=30,n_iter=1000, init='pca',random_state=42, metric="jaccard")
tsne_results = tsne.fit_transform(data_tsne)
tsne_results

# Choosing complentary information
label = data1[['SMILES_curated', 'Database']]
label = label.to_numpy()
print(label.shape)
# Concat arrays
arr = np.concatenate((label, tsne_results), axis = 1)
print(arr.shape)
# New dataframe
tsne_dataset = pd.DataFrame(data=arr, columns = ['SMILES_curated','Database','axis 1', 'axis 2'] )
tsne_dataset

"""## Visualization"""

FinalSet=tsne_dataset.copy()
fig, ax1 = plt.subplots (1,1, figsize=(16,11), dpi=600, sharey=True)

A=ax1.scatter(FinalSet[FinalSet["Database"] == "smHD8_Druglike"]["axis 1"], FinalSet[FinalSet["Database"] == "smHD8_Druglike"]["axis 2"], s=20,c="cadetblue")
B=ax1.scatter(FinalSet[FinalSet["Database"] == "smHD8_HighDiv"]["axis 1"], FinalSet[FinalSet["Database"] == "smHD8_HighDiv"]["axis 2"], s=20,c="mediumorchid")


ax1.set_xlim(-50, 50)
ax1.set_ylim(-50, 50)
plt.rc('xtick',labelsize=16)
plt.rc('ytick',labelsize=16)
#ax1.set_title("Chemical space visualization of all compounds using t-SNE", fontsize=20, pad=20)

fig.legend((A, B),('smHD8_Druglike', 'smHD8_HighDiv'),
           loc="lower center", bbox_to_anchor=(0.5, 0.01), borderaxespad=0,
           scatterpoints=300,
           ncol=10,
           fontsize=16
         )
ax1.set_xlabel("t-SNE Axis 1", fontsize=18)
ax1.set_ylabel("t-SNE Axis 2", fontsize=18)

plt.show()
fig.savefig("TSNE_allCompounds_denovo_morgan2.jpg", bbox_inches='tight', pad_inches=0)

FinalSet=tsne_dataset.copy()
fig, (ax1,ax2,ax3) = plt.subplots (1,3, figsize=(15,5), dpi=600, sharey=True)

A=ax1.scatter(FinalSet[FinalSet["Database"] == "smHD8_Druglike"]["axis 1"], FinalSet[FinalSet["Database"] == "smHD8_Druglike"]["axis 2"], s=10,c="cadetblue")
B=ax1.scatter(FinalSet[FinalSet["Database"] == "smHD8_HighDiv"]["axis 1"], FinalSet[FinalSet["Database"] == "smHD8_HighDiv"]["axis 2"], s=10,c="mediumorchid")

ax2.scatter(FinalSet[FinalSet["Database"] == "smHD8_Druglike"]["axis 1"], FinalSet[FinalSet["Database"] == "smHD8_Druglike"]["axis 2"], s=10,c="cadetblue")

ax3.scatter(FinalSet[FinalSet["Database"] == "smHD8_HighDiv"]["axis 1"], FinalSet[FinalSet["Database"] == "smHD8_HighDiv"]["axis 2"], s=10,c="mediumorchid")

ax1.set_title("(A)", fontsize=16)
ax2.set_title("(B)", fontsize=16)
ax3.set_title("(C)", fontsize=16)


ax1.set_xlim(-50,50)
ax2.set_xlim(-50,50)
ax3.set_xlim(-50,50)


ax1.set_ylim(-50,50)
plt.rc('xtick',labelsize=16)
plt.rc('ytick',labelsize=16)

fig.legend((A, B),('smHD8_Druglike', 'smHD8_HighDiv'),
           loc="lower center", bbox_to_anchor=(0.5, 0.0015), borderaxespad=0,
           scatterpoints=200,
           ncol=2,
           fontsize=12)

plt.show()
fig.savefig("t-SNE_denovo_morgan2.jpg", bbox_inches='tight', pad_inches=0)

FinalSet=tsne_dataset.copy()
fig, ax1 = plt.subplots (1,1, figsize=(16,11), dpi=600, sharey=True)

A=ax1.scatter(FinalSet[FinalSet["Database"] == "smHD8_HighDiv"]["axis 1"], FinalSet[FinalSet["Database"] == "smHD8_HighDiv"]["axis 2"], s=20,c="mediumorchid")

ax1.set_xlim(-50, 50)
ax1.set_ylim(-50, 50)
plt.rc('xtick',labelsize=16)
plt.rc('ytick',labelsize=16)
#plt.scatter(x=tsne_dataset["axis 1"], y=tsne_dataset["axis 2"], s=200, )
#ax1.set_title("Chemical space visualization of all compounds using t-SNE", fontsize=20, pad=20)

fig.legend((A,), ['smHD8_HighDiv',],
           loc="lower center", bbox_to_anchor=(0.5, 0.01), borderaxespad=0,
           scatterpoints=300,
           ncol=10,
           fontsize=16
         )
ax1.set_xlabel("t-SNE Axis 1", fontsize=18)
ax1.set_ylabel("t-SNE Axis 2", fontsize=18)

plt.show()
fig.savefig("TSNE_allCompounds_smHD8_HighDiv_Morgan2.jpg", bbox_inches='tight', pad_inches=0)

FinalSet=tsne_dataset.copy()
fig, ax1 = plt.subplots (1,1, figsize=(16,11), dpi=600, sharey=True)

A=ax1.scatter(FinalSet[FinalSet["Database"] == "smHD8_Druglike"]["axis 1"], FinalSet[FinalSet["Database"] == "smHD8_Druglike"]["axis 2"], s=20,c="cadetblue")

ax1.set_xlim(-50, 50)
ax1.set_ylim(-50, 50)
plt.rc('xtick',labelsize=16)
plt.rc('ytick',labelsize=16)
#plt.scatter(x=tsne_dataset["axis 1"], y=tsne_dataset["axis 2"], s=200, )
#ax1.set_title("Chemical space visualization of all compounds using t-SNE", fontsize=20, pad=20)

fig.legend((A,), ['smHD8_Druglike',],
           loc="lower center", bbox_to_anchor=(0.5, 0.01), borderaxespad=0,
           scatterpoints=300,
           ncol=10,
           fontsize=16
         )
ax1.set_xlabel("t-SNE Axis 1", fontsize=18)
ax1.set_ylabel("t-SNE Axis 2", fontsize=18)

plt.show()
fig.savefig("TSNE_allCompounds_smHD8_Druglike_Morgan2.jpg", bbox_inches='tight', pad_inches=0)